PIVOT-6587 Add script to load any sandbox app in MAC  (#100)
* PIVOT-6587 Add script to load any sandbox app in MAC

* Use variables for jar versions

* Add check on Mbean output

* Add basic framework for scripted queries on MAC cube

* Add missing cleanup step & add logs to gitignore

* Changes after review

* Cleanup & add repo url as script variable

* Update script

* Apply changes from PIVOT-6591

* Split the script into two

* PIVOT-6591 Add github action to modularize the mac CI (#103)

* Bump wait time on load to pass CI

* Fix github action blocking step

* Update .github/PULL_REQUEST_TEMPLATE.md

Co-authored-by: Mahieddine Dellabani <mahieddine.dellabani@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,15 @@
 version: 2.1
 
+parameters:
+  head_ref:
+    type: string
+    default: NONE
+  base_ref:
+    type: string
+    default: NONE
+  run_compatibility:
+    type: boolean
+    default: false
 executors:
   jdk11-docker:
     docker:
@@ -13,7 +23,6 @@ executors:
       LC_ALL: C.UTF-8
     machine:
       image: ubuntu-2004:202201-02
-      docker_layer_caching: true
 
 jobs:
   build_and_test:
@@ -43,11 +52,34 @@ jobs:
           paths: [ ~/.m2/repository ]
           key: mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}
 
-  sonar_analysis:
-    executor: jdk11-docker
-    # A large machine is needed to perform the whole analysis, as it requires a lot of memory
+  launch_compatibility_checks:
+    executor: vm
+    resource_class: medium
+    steps:
+      - unless:
+          condition: <<pipeline.parameters.run_compatibility>>
+          steps:
+            - run:
+                name: Fail if no compatibility enabled
+                command: exit 1
+      - when:
+          condition: <<pipeline.parameters.run_compatibility>>
+          steps:
+            - checkout
+# Somehow fails on ubuntu 20.04 (https://askubuntu.com/questions/1240056/unable-to-install-libxml2-utils-on-ubuntu-20-04-wsl)
+#            - run:
+#               name: Try downloading xmllint
+#               command: sudo apt-get install libxml2-utils
+            - run:
+                name: Compatibility enabled, fetch matching releases using artifacts.activeviam.com
+                command: bash ./scripts/get_compatible_ap_releases.sh
+  compatibility_check:
+    executor: vm
     resource_class: large
-    working_directory: ~/activepivot
+    working_directory: ~/mac
+    parameters:
+      ap-version:
+        type: string
     steps:
       - checkout
       - restore_cache:
@@ -55,20 +87,81 @@ jobs:
             - mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}
             - mac-java-{{ .Branch }}-
             - mac-java-
+            - mac-export-<< parameters.ap-version >>-{{ checksum "pom.xml" }}
       - run:
-          name: Analyze project
+          name: "Run sandbox memory export"
           command: |
-            mvn -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN sonar:sonar
-
-
+            sudo sysctl -w vm.overcommit_memory=1 && \
+            # using cached exports if available
+            if [[ ! -d ${PWD}/target/exported_statistics || -z $(ls -A ${PWD}/target/exported_statistics) ]]; then
+              echo "No available export cache : Run sandbox export script."
+              bash ./scripts/sandbox_export_generator.sh << parameters.ap-version >> "${ARTIFACTS_USER}:${ARTIFACTS_PASSWORD}"
+            else
+              echo "Use available export cache."
+            fi
+      - run:
+          name: "Run checks on export"
+          command: bash ./scripts/mac_export_load.sh $(cat ./logs/jmxterm.log | tail -1) << parameters.ap-version >>
+      - store_artifacts:
+          path: ./logs
+      - save_cache:
+          paths: [ target/exported_statistics ]
+          key: mac-export-<< parameters.ap-version >>-{{ checksum "pom.xml" }}
 workflows:
   version: 2
   check:
-    triggers:
     jobs:
       - build_and_test:
-          filters:
-            branches:
-              ignore:
-                - /5.\d+/
           context: rnd-server
+      - launch_compatibility_checks:
+          context: rnd-server
+          requires:
+            - build_and_test
+      - compatibility_check:
+          matrix:
+            parameters:
+              ap-version: [
+                  "5.9.0",
+                  "5.9.1",
+                  "5.9.2",
+                # The following two versions have their export broken (NPE on export)
+                # "5.9.3",
+                # "5.9.4",
+                  "5.9.5",
+                  "5.9.6",
+                  "5.9.7",
+                  "5.9.8",
+                  "5.9.9",
+                  "5.9.10",
+                  "5.9.11",
+                  "5.9.12",
+                  "5.9.13",
+                # Early releases of the 5.10 sandbox have a dependency on a now removed ActiveUI snapshot : activeui:jar:5.0.0-beta-20210224125715-19abcee
+                # "5.10.0",
+                # "5.10.1",
+                # "5.10.2",
+                  "5.10.3",
+                  "5.10.4",
+                  "5.10.5",
+                  "5.10.6",
+                  "5.10.7",
+                  "5.10.8",
+                  "5.10.9",
+                  "5.10.10",
+                  "5.10.11",
+                  "5.10.12",
+                  "5.10.13",
+                # Early releases of the 5.11 sandbox have a dependency on a now removed ActiveUI snapshot : activeui:jar:5.0.4-20211117104705-da07c29
+                # "5.11.0",
+                  "5.11.1",
+                  "5.11.2",
+                  "5.11.3",
+                  "5.11.4",
+                  "5.11.5",
+                  "6.0.0",
+                  "6.0.1",
+                  "6.0.2"
+              ]
+          context: rnd-server
+          requires:
+            - launch_compatibility_checks
